services:
  music-hub:
    container_name: music-hub
    image: docker-registry.hanwool.dev/music-hub
    expose:
      - 8080
    ports:
      - 16140:8080
    env_file:
      - ../.env
    environment:
      TZ: Asia/Seoul
    networks:
      - itcen-backend

networks:
  itcen-backend:
    external: true
