version: "3"

services:
  music:
    container_name: music
    image: weatherdecenhub.store/music-hub
    expose:
      - 8080
    ports:
      - 80:8080
    env_file:
      - .env        # 이 한 줄로 모든 환경변수를 로드함
    environment:
      TZ: Asia/Seoul
    networks:
      - backend

networks:
  backend:
    external: true