spring.application.name=backend

# OpenAI
openai.model=${OPENAI_MODEL}
openai.api.key=${OPENAI_API_KEY}
openai.api.url=${OPENAI_API_URL}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Spotify
spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}

# YouTube
youtube.client.api-key=${YOUTUBE_API_KEY}

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.forward-headers-strategy=framework