name: Hanwool Java CI with Maven & Remote Build

on:
  push:
    branches: [ "develop-hanwool" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HANWOOL_SSH_HOST }}
          username: ${{ secrets.HANWOOL_SSH_USERNAME }}
          key: ${{ secrets.HANWOOL_SSH_KEY }}
          port: ${{ secrets.HANWOOL_SSH_PORT_NUMBER }}
          source: "target/*.jar,Dockerfile,docker-compose-back.yaml"
          target: ${{ secrets.HANWOOL_WORK_DIR }}/music-hub

      - name: SSH Remote Build and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HANWOOL_SSH_HOST }}
          username: ${{ secrets.HANWOOL_SSH_USERNAME }}
          key: ${{ secrets.HANWOOL_SSH_KEY }}
          port: ${{ secrets.HANWOOL_SSH_PORT_NUMBER }}
          script: |
            cd ${{ secrets.HANWOOL_WORK_DIR }}/music-hub
            
            echo "${{ secrets.HANWOOL_REGISTRY_PASSWORD }}" | docker login ${{ secrets.HANWOOL_REGISTRY_HOST }} -u ${{ secrets.HANWOOL_REGISTRY_USER }} --password-stdin
            
            docker build -t ${{ secrets.HANWOOL_REGISTRY_HOST }}/music-hub:latest .
            docker push ${{ secrets.HANWOOL_REGISTRY_HOST }}/music-hub:latest
            
            docker compose -f docker-compose-back.yaml down || true
            docker compose -f docker-compose-back.yaml up -d
            docker image prune -f