name: Java CI with Maven & CodeDeploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build and Push ARM64 Docker Image (blue)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.REGISTRY_HOST }}/itcen-back-blue:latest \
            --push .

      - name: Generate .env and .env.docker file from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create deployable zip
        run: |
          mkdir deploy
          cp ./appspec.yml ./deploy/
          cp ./deploy.sh ./deploy/
          cp ./docker-compose-back.yaml ./deploy/
          cp .env ./deploy/
          zip -r -qq -j ./$GITHUB_SHA.zip ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./$GITHUB_SHA.zip s3://${{ secrets.BUCKET_NAME }}/${{ secrets.BUCKET_PREFIX }}/$GITHUB_SHA.zip \
            --region ${{ secrets.AWS_REGION }}

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name custom \
            --deployment-group-name custom \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},bundleType=zip,key=${{ secrets.BUCKET_PREFIX }}/$GITHUB_SHA.zip \
            --region ${{ secrets.AWS_REGION }}